In [1]:
import polars as pl
path= "Carteras.parquet"
hist_investments=pl.read_parquet(path)

In [3]:
hist_investments.select("tipo_de_instrumento").unique()

shape: (106, 1)
┌─────────────────────┐
│ tipo_de_instrumento │
│ ---                 │
│ str                 │
╞═════════════════════╡
│ CMEV                │
│ YNMC                │
│ VIPE                │
│ BEU                 │
│ CFMD                │
│ …                   │
│ TBE                 │
│ PRC                 │
│ DEB                 │
│ FII                 │
│ BVL                 │
└─────────────────────┘

In [2]:
hist_investments.head(10)

shape: (10, 19)
┌──────────┬─────┬────────────┬────────────┬───┬────────────┬────────────┬────────────┬────────────┐
│ fecha    ┆ afp ┆ tipo_de_fo ┆ tipo_de_in ┆ … ┆ plazo_econ ┆ tasa_pacta ┆ tasa_pacta ┆ tasa_pacta │
│ ---      ┆ --- ┆ ndo        ┆ strumento  ┆   ┆ omico      ┆ da_del_fon ┆ da_de_la_c ┆ da_de_la_c │
│ str      ┆ str ┆ ---        ┆ ---        ┆   ┆ ---        ┆ do_swap    ┆ ontraparte ┆ ontraparte │
│          ┆     ┆ str        ┆ str        ┆   ┆ i64        ┆ ---        ┆ …          ┆ …          │
│          ┆     ┆            ┆            ┆   ┆            ┆ str        ┆ ---        ┆ ---        │
│          ┆     ┆            ┆            ┆   ┆            ┆            ┆ str        ┆ str        │
╞══════════╪═════╪════════════╪════════════╪═══╪════════════╪════════════╪════════════╪════════════╡
│ 19960731 ┆ apo ┆ C          ┆ ACC        ┆ … ┆ null       ┆ .          ┆ .          ┆ null       │
│ 19960731 ┆ apo ┆ C          ┆ ACC        ┆ … ┆ null       ┆ .          ┆ .          ┆ null       │
│ 19960731 ┆ apo ┆ C          ┆ ACC        ┆ … ┆ null       ┆ .          ┆ .          ┆ null       │
│ 19960731 ┆ apo ┆ C          ┆ ACC        ┆ … ┆ null       ┆ .          ┆ .          ┆ null       │
│ 19960731 ┆ apo ┆ C          ┆ ACC        ┆ … ┆ null       ┆ .          ┆ .          ┆ null       │
│ 19960731 ┆ apo ┆ C          ┆ ACC        ┆ … ┆ null       ┆ .          ┆ .          ┆ null       │
│ 19960731 ┆ apo ┆ C          ┆ ACC        ┆ … ┆ null       ┆ .          ┆ .          ┆ null       │
│ 19960731 ┆ apo ┆ C          ┆ ACC        ┆ … ┆ null       ┆ .          ┆ .          ┆ null       │
│ 19960731 ┆ apo ┆ C          ┆ ACC        ┆ … ┆ null       ┆ .          ┆ .          ┆ null       │
│ 19960731 ┆ apo ┆ C          ┆ ACC        ┆ … ┆ null       ┆ .          ┆ .          ┆ null       │
└──────────┴─────┴────────────┴────────────┴───┴────────────┴────────────┴────────────┴────────────┘